apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-checkoutservice
  namespace: development
  labels:
    app: checkoutservice
spec:
  template:
    spec:
      containers:
      - name: checkoutservice
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
