apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-dev
  namespace: development
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: kumarsinganamalla093@gmail.com
    privateKeySecretRef:
      name: letsencrypt-dev-account-key
    solvers:
    - http01:
        ingress:
          class: nginx
