apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: development

namePrefix: dev-
resources:
  - ../../Base/Adservice
  - ../../Base/Cartservice
  - ../../Base/Emailservice
  - ../../Base/Genric
  - ../../Base/Productcatalogservice
  - ../../Base/Redis
  - ../../Base/checkoutservice
  - ../../Base/currencyservice
  - ../../Base/frontendservice
  - ../../Base/paymentservice
  - ../../Base/recommendationservice
  - ../../Base/shippingservice
  - Serviceaccount.yaml
  - ingress.yaml
  - HPA.yaml
  - Namespace.yaml



patches:
  - target:
      kind: StatefulSet
      name: redis
      
    patch: |-
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/resources/requests/storage
        value: 5Gi

  - path: adservice-Limits.yaml
    target:
      kind: Deployment
      name: adservice

  - path: cartservice-Limits.yaml
    target:
      kind: Deployment
      name: cartservice

  - path: checkoutservice-Limits.yaml
    target:
      kind: Deployment
      name: checkoutservice

  - path: currencyservice-Limits.yaml
    target:
      kind: Deployment
      name: currencyservice

  - path: emailservice-Limits.yaml
    target:
      kind: Deployment
      name: emailservice

  - path: frontendservice-Limits.yaml
    target:
      kind: Deployment
      name: frontendservice

  - path: paymentservice-Limits.yaml
    target:
      kind: Deployment
      name: paymentservice

  - path: productcatalogservice-Limits.yaml
    target:
      kind: Deployment
      name: productcatalogservice

  - path: recommendationservice-Limits.yaml
    target:
      kind: Deployment
      name: recommendationservice

  - path: shippingservice-Limits.yaml
    target:
      kind: Deployment
      name: shippingservice
    