apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: development

namePrefix: dev-
resources:
  - ../../base
  - serviceaccount.yaml
  - ingress.yaml

patchesStrategicMerge:
  - Patch-resourcelimit.yaml
  - Patch-Redis.yaml