apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: development

namePrefix: dev-
resources:
  - ../../Base/Adservice
  - ../../Base/Cartservice
  - ../../Base/Emailservice
  - ../../Base/Genric
  - ../../Base/Productcatalogservice
  - ../../Base/Redis
  - ../../Base/Checkoutservice
  - ../../Base/Currencyservice
  - ../../Base/Frontendservice
  - ../../Base/Paymentservice
  - ../../Base/Recommendationservice
  - ../../Base/Shippingservice
  - serviceaccount.yaml
  - ingress.yaml
  - HPA.yaml
  - namespace.yaml



patches:
  - path: Patch-Redis.yaml
    target:
      kind: StatefulSet
      name: redis
      namespace: development
  - path: Patch-resourcelimit.yaml
    target:
      namespace: development
    