apiVersion: v1
kind: ConfigMap
metadata:
  name: microservices-config
data:
  AD_SERVICE_ADDR: "adservice:9555"
  CURRENCY_SERVICE_ADDR: "currencyservice:7000"
  CART_SERVICE_ADDR: "cartservice:7070"
  CHECKOUT_SERVICE_ADDR: "checkoutservice:5050"
  EMAIL_SERVICE_ADDR: "emailservice:8081"
  FRONTEND_SERVICE_ADDR: "frontendservice:8080"
  PRODUCT_CATALOG_SERVICE_ADDR: "productcatalogservice:3550"
  PAYMENT_SERVICE_ADDR: "paymentservice:50051"
  RECOMMENDATION_SERVICE_ADDR: "recommendationservice:8082"
  SHIPPING_SERVICE_ADDR: "shippingservice:50052"
  SHOPPING_ASSISTANT_SERVICE_ADDR: "shoppingassistantservice:80"
  REDIS_ADDR: "redis:6379"
  
  
  
