apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: development
  labels:
    app: dev-redis
spec:
  serviceName: redis
  template:
    spec:
      containers:
      - name: redis
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
