kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: frontendservice-policy
spec:
  podSelector:
    matchLabels:
      app: frontendservice
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: checkoutservice
    - podSelector:
        matchLabels:
          app: productcatalogservice
    - podSelector:
        matchLabels:
          app: recommendationservice
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: shoppingassistantservice
    ports:
    - protocol: TCP
      port: 8080      
  - to:
    - podSelector:
        matchLabels:
          app: adservice
    ports:
    - protocol: TCP
      port: 9555      
  - to:
    - podSelector:
        matchLabels:
          app: shippingservice
    ports:
    - protocol: TCP
      port: 50051
  - to:
    - podSelector:
        matchLabels:
          app: cartservice
    ports:
    - protocol: TCP
      port: 7070
  - to:
    - podSelector:
        matchLabels:
          app: currencyservice
    ports:
    - protocol: TCP
      port: 7000
  - to:
    - podSelector:
        matchLabels:
          app: productcatalogservice
    ports:
    - protocol: TCP
      port: 3550
  - to:
    - podSelector:
        matchLabels:
          app: checkoutservice
    ports:
    - protocol: TCP
      port: 5050
  - to:
    - podSelector:
        matchLabels:
          app: recommendationservice
    ports:
    - protocol: TCP
      port: 8080
