kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: recommendationservice-np
spec:
  podSelector:
    matchLabels:
      app: recommendationservice
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: frontendservice
    ports:
    - protocol: TCP
      port: 8080    
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: productcatalogservice
    ports:
    - protocol: TCP
      port: 3550
