apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: "redis"
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
          - containerPort: 6379
        readinessProbe:
          tcpSocket:
            port: 6379
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 6379
          periodSeconds: 5
        volumeMounts:
          - name: redis-storage
            mountPath: /data/redis
      affinity: 
        nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: disk
              operator: In
              values:
              - ssd
    