apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prod-
namespace: production

resources:
  - ../../Base/Adservice
  - ../../Base/Cartservice
  - ../../Base/Emailservice
  - ../../Base/Genric
  - ../../Base/Productcatalogservice
  - ../../Base/Redis
  - ../../Base/Checkoutservice
  - ../../Base/Currencyservice
  - ../../Base/Frontendservice
  - ../../Base/Paymentservice
  - ../../Base/Recommendationservice
  - ../../Base/Shippingservice
  - Serviceaccount.yaml
  - ingress.yaml
  - Namspace.yaml

patchesStrategicMerge:
  - Patch-resourcelimit.yaml
  - Patch-Redis.yaml  

