apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prod-
namespace: production

resources:
  - ../../base
  - serviceaccount.yaml

patchesStrategicMerge:
  - Patch-resourcelimit.yaml
  - Patch-Redis.yaml  
