apiVersion: v1
kind: Service
metadata:
  name: Emailservice
  labels:
    app: Emailservice
spec:
  type: ClusterIP
  selector:
    app: Emailservice
  ports:
  - name: grpc
    port: 8081        # Service port (used inside cluster)
    targetPort: 8080  # Pod's containerPort