apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
  labels:
    app: currencyservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      containers:
      - name: currencyservice
        image: prasannakumarsinganamalla431/currencyservice:latest
        ports:
          - containerPort: 7000
        env:
          - name: PORT
            value: "7000"
          - name: DISABLE_PROFILER
            value: "true"
        readinessProbe:
          grpc:
            port: 7000
          initialDelaySeconds: 10   # wait before first check
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
        livenessProbe:
          grpc:
            port: 7000
          initialDelaySeconds: 20  # After the container starts, Kubernetes waits 10 seconds before running the first probe. 
          periodSeconds: 10 # How often (in seconds) Kubernetes will run the probe. 
          timeoutSeconds: 2 # How long Kubernetes waits for a response before considering the probe failed. 
          failureThreshold: 3 # How many consecutive failures before Kubernetes considers the container unhealthy (for liveness) or not ready (for readiness). 
              