apiVersion: apps/v1
kind: Deployment
metadata:
  name: Paymentservice
  labels:
    app: Paymentservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - name: paymentservice
        image: prasannakumarsinganamalla431/paymentservice:latest
        ports:
          - containerPort: 50051
        env:
          - name: PORT
            value: "50051"
          - name: DISABLE_PROFILER
            value: "true"
        readinessProbe:
          grpc:
            port: 50051
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
        livenessProbe:
          grpc:
            port: 50051
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - paymentservice
              topologyKey: "kubernetes.io/hostname"                      
